module.exports = function (app) {
    app.get('/', (_, res) => res.send("Hello World!"));
    // ADMIN route shu yerga chaqiriladi...
    // USER route shu yerga chaqiriladi...
    // PRODUCT route shu yerga chaqiriladi...
    // CATEGORY route shu yerga chaqiriladi...
};